
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.wanderariel;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int MINUS = 3;
  public static final int GOATED = 5;
  public static final int DANZARIN = 11;
  public static final int NUMBER = 4;
  public static final int RAYO = 10;
  public static final int COMETA = 13;
  public static final int SALTARIN = 12;
  public static final int EOF = 0;
  public static final int PLUS = 2;
  public static final int RELAMPAGO = 9;
  public static final int error = 1;
  public static final int IDENTIFIER = 6;
  public static final int RODOLFO = 7;
  public static final int TRUENO = 8;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PLUS",
  "MINUS",
  "NUMBER",
  "GOATED",
  "IDENTIFIER",
  "RODOLFO",
  "TRUENO",
  "RELAMPAGO",
  "RAYO",
  "DANZARIN",
  "SALTARIN",
  "COMETA"
  };
}

